server:
  port: 8080
app:
  client2-list-page:
    msg: Коля любит Мамбу!!!
spring:
  datasource:
    url: jdbc:postgresql://192.168.10.173:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE