server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://192.168.10.173:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  rabbitmq:
    addresses: "192.168.10.173"
  listener:
    simple:
      default-requeue-rejected: false
  main:
    allow-circular-references: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE
kladr:
  url: https://kladr-api.ru/api.php?contentType=building&withParent=1&zip=
